name: spin
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - ld_impl_linux-64=2.44
  - libexpat=2.7.4
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libmpdec=4.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.19
  - packaging=25.0
  - pip=25.3
  - pthread-stubs=0.3
  - python=3.13.11
  - python_abi=3.13
  - readline=8.3
  - setuptools=80.10.2
  - sqlite=3.51.1
  - tk=8.6.15
  - tzdata=2025c
  - wheel=0.46.3
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - abnf==2.2.0
      - accelerate==1.12.0
      - annotated-types==0.7.0
      - anyio==4.12.1
      - attrs==25.4.0
      - backoff==2.2.1
      - bcrypt==5.0.0
      - blis==1.3.3
      - build==1.4.0
      - cachetools==7.0.0
      - catalogue==2.0.10
      - certifi==2026.1.4
      - cffi==2.0.0
      - chardet==5.2.0
      - charset-normalizer==3.4.4
      - chromadb==1.4.1
      - cint==1.0.0
      - click==8.3.1
      - cloudpathlib==0.23.0
      - confection==0.1.5
      - contourpy==1.3.3
      - cryptography==46.0.4
      - cuda-bindings==12.9.4
      - cuda-pathfinder==1.3.3
      - cycler==0.12.1
      - cymem==2.0.13
      - diskcache==5.6.3
      - distro==1.9.0
      - durationpy==0.10
      - fickling==0.1.7
      - filelock==3.20.3
      - flatbuffers==25.12.19
      - fonttools==4.61.1
      - fsspec==2026.2.0
      - gensim==4.4.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - googleapis-common-protos==1.72.0
      - gql==4.0.0
      - graphql-core==3.2.7
      - graphviz==0.21
      - grpcio==1.78.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.36.2
      - idna==3.11
      - importlib-metadata==8.7.1
      - importlib-resources==6.5.2
      - intervaltree==3.2.1
      - jinja2==3.1.6
      - jiter==0.13.0
      - joblib==1.5.3
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - kaitaistruct==0.11
      - kiwisolver==1.4.9
      - kubernetes==35.0.0
      - langchain-chroma==1.1.0
      - langchain-core==1.2.9
      - langchain-huggingface==1.2.0
      - langchain-openai==1.1.7
      - langsmith==0.6.9
      - levenshtein==0.27.3
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - mmh3==5.2.0
      - mpmath==1.3.0
      - multidict==6.7.1
      - murmurhash==1.0.15
      - networkx==3.6.1
      - nltk==3.9.2
      - numpy==2.4.2
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.8.90
      - oauthlib==3.3.1
      - onnxruntime==1.24.1
      - openai==2.17.0
      - opentelemetry-api==1.39.1
      - opentelemetry-exporter-otlp-proto-common==1.39.1
      - opentelemetry-exporter-otlp-proto-grpc==1.39.1
      - opentelemetry-proto==1.39.1
      - opentelemetry-sdk==1.39.1
      - opentelemetry-semantic-conventions==0.60b1
      - orjson==3.11.7
      - overrides==7.7.0
      - pandas==3.0.0
      - pdfminer-six==20260107
      - pillow==12.1.0
      - platformdirs==4.5.1
      - polyfile-weave==0.5.9
      - posthog==5.4.0
      - preshed==3.0.12
      - propcache==0.4.1
      - protobuf==6.33.5
      - psutil==7.2.2
      - pybase64==1.4.3
      - pycparser==3.0
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - pyparsing==3.3.2
      - pypika==0.51.1
      - pyproject-hooks==1.2.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - python-levenshtein==0.27.3
      - pyyaml==6.0.3
      - rapidfuzz==3.14.3
      - referencing==0.37.0
      - regex==2026.1.15
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - requests-toolbelt==1.0.0
      - rich==14.3.2
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - seaborn==0.13.2
      - sentence-transformers==5.2.2
      - sentry-sdk==2.52.0
      - shellingham==1.5.4
      - six==1.17.0
      - smart-open==7.5.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - spacy==3.8.11
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - spin==0.1
      - srsly==2.5.2
      - stdlib-list==0.11.1
      - sympy==1.14.0
      - tenacity==9.1.4
      - thinc==8.3.10
      - threadpoolctl==3.6.0
      - tiktoken==0.12.0
      - tokenizers==0.22.2
      - torch==2.10.0
      - tqdm==4.67.3
      - transformers==4.57.6
      - triton==3.6.0
      - typer==0.21.1
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.3
      - uuid-utils==0.14.0
      - uvicorn==0.40.0
      - uvloop==0.22.1
      - wandb==0.24.2
      - wasabi==1.1.3
      - watchfiles==1.1.1
      - weasel==0.4.3
      - weave==0.52.26
      - websocket-client==1.9.0
      - websockets==16.0
      - wrapt==2.1.1
      - xxhash==3.6.0
      - yarl==1.22.0
      - zipp==3.23.0
      - zstandard==0.25.0
prefix: /home/tjas/miniconda3/envs/spin
